name: Sonar Analysis
on:
  # Can be run manually
  workflow_dispatch:

  # on workflow run
  workflow_run:
    workflows:
      - Test
      - Release
    types:
      - completed

# Only one run per branch at a time
concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qc:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    uses: panates/github-actions/.github/workflows/sonar.yaml@v1
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
