name: Test
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:

  # Can be run manually
  workflow_dispatch:

  # on git push
  push:
    branches:
      - dev

# Only one run per branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ***********************************
  # Job: Test
  # ***********************************
  test:
    name: 'Tests'
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'push' &&
        !(
          contains(github.event.head_commit.message, 'no-test') ||
          ( 
            startsWith(github.event.head_commit.message, 'Merge pull request') &&
            contains(github.event.head_commit.message, '/dev')
          )
        )
      )
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Setup Environment
        uses: panates/gh-setup-node@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Apply tests
        run: |
          npm run qc
          npm run citest
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
